// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yacs5e.proto

/*
Package yacs5e is a generated protocol buffer package.

It is generated from these files:
	yacs5e.proto

It has these top-level messages:
	TUser
	TCharacter
	TTalk
	Empty
*/
package yacs5e

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TUser struct {
	Login       string `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Id          uint32 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	RespToken   string `protobuf:"bytes,4,opt,name=respToken" json:"respToken,omitempty"`
	VisibleName string `protobuf:"bytes,5,opt,name=visibleName" json:"visibleName,omitempty"`
}

func (m *TUser) Reset()                    { *m = TUser{} }
func (m *TUser) String() string            { return proto.CompactTextString(m) }
func (*TUser) ProtoMessage()               {}
func (*TUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TUser) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *TUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TUser) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TUser) GetRespToken() string {
	if m != nil {
		return m.RespToken
	}
	return ""
}

func (m *TUser) GetVisibleName() string {
	if m != nil {
		return m.VisibleName
	}
	return ""
}

type TCharacter struct {
	Uuid     string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	LastSync uint64 `protobuf:"varint,2,opt,name=last_sync,json=lastSync" json:"last_sync,omitempty"`
	LastMod  uint64 `protobuf:"varint,3,opt,name=last_mod,json=lastMod" json:"last_mod,omitempty"`
	Blob     string `protobuf:"bytes,4,opt,name=blob" json:"blob,omitempty"`
	Delete   bool   `protobuf:"varint,5,opt,name=delete" json:"delete,omitempty"`
}

func (m *TCharacter) Reset()                    { *m = TCharacter{} }
func (m *TCharacter) String() string            { return proto.CompactTextString(m) }
func (*TCharacter) ProtoMessage()               {}
func (*TCharacter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TCharacter) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TCharacter) GetLastSync() uint64 {
	if m != nil {
		return m.LastSync
	}
	return 0
}

func (m *TCharacter) GetLastMod() uint64 {
	if m != nil {
		return m.LastMod
	}
	return 0
}

func (m *TCharacter) GetBlob() string {
	if m != nil {
		return m.Blob
	}
	return ""
}

func (m *TCharacter) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

type TTalk struct {
	// Types that are valid to be assigned to Union:
	//	*TTalk_User
	//	*TTalk_Character
	//	*TTalk_Good
	Union isTTalk_Union `protobuf_oneof:"union"`
}

func (m *TTalk) Reset()                    { *m = TTalk{} }
func (m *TTalk) String() string            { return proto.CompactTextString(m) }
func (*TTalk) ProtoMessage()               {}
func (*TTalk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isTTalk_Union interface {
	isTTalk_Union()
}

type TTalk_User struct {
	User *TUser `protobuf:"bytes,1,opt,name=user,oneof"`
}
type TTalk_Character struct {
	Character *TCharacter `protobuf:"bytes,2,opt,name=character,oneof"`
}
type TTalk_Good struct {
	Good bool `protobuf:"varint,3,opt,name=good,oneof"`
}

func (*TTalk_User) isTTalk_Union()      {}
func (*TTalk_Character) isTTalk_Union() {}
func (*TTalk_Good) isTTalk_Union()      {}

func (m *TTalk) GetUnion() isTTalk_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *TTalk) GetUser() *TUser {
	if x, ok := m.GetUnion().(*TTalk_User); ok {
		return x.User
	}
	return nil
}

func (m *TTalk) GetCharacter() *TCharacter {
	if x, ok := m.GetUnion().(*TTalk_Character); ok {
		return x.Character
	}
	return nil
}

func (m *TTalk) GetGood() bool {
	if x, ok := m.GetUnion().(*TTalk_Good); ok {
		return x.Good
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TTalk) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TTalk_OneofMarshaler, _TTalk_OneofUnmarshaler, _TTalk_OneofSizer, []interface{}{
		(*TTalk_User)(nil),
		(*TTalk_Character)(nil),
		(*TTalk_Good)(nil),
	}
}

func _TTalk_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TTalk)
	// union
	switch x := m.Union.(type) {
	case *TTalk_User:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.User); err != nil {
			return err
		}
	case *TTalk_Character:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Character); err != nil {
			return err
		}
	case *TTalk_Good:
		t := uint64(0)
		if x.Good {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("TTalk.Union has unexpected type %T", x)
	}
	return nil
}

func _TTalk_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TTalk)
	switch tag {
	case 1: // union.user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TUser)
		err := b.DecodeMessage(msg)
		m.Union = &TTalk_User{msg}
		return true, err
	case 2: // union.character
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TCharacter)
		err := b.DecodeMessage(msg)
		m.Union = &TTalk_Character{msg}
		return true, err
	case 3: // union.good
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Union = &TTalk_Good{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _TTalk_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TTalk)
	// union
	switch x := m.Union.(type) {
	case *TTalk_User:
		s := proto.Size(x.User)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TTalk_Character:
		s := proto.Size(x.Character)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TTalk_Good:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*TUser)(nil), "TUser")
	proto.RegisterType((*TCharacter)(nil), "TCharacter")
	proto.RegisterType((*TTalk)(nil), "TTalk")
	proto.RegisterType((*Empty)(nil), "Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for YACS5E service

type YACS5EClient interface {
	Registration(ctx context.Context, in *TUser, opts ...grpc.CallOption) (*Empty, error)
	Login(ctx context.Context, in *TUser, opts ...grpc.CallOption) (*Empty, error)
	Synchronize(ctx context.Context, opts ...grpc.CallOption) (YACS5E_SynchronizeClient, error)
}

type yACS5EClient struct {
	cc *grpc.ClientConn
}

func NewYACS5EClient(cc *grpc.ClientConn) YACS5EClient {
	return &yACS5EClient{cc}
}

func (c *yACS5EClient) Registration(ctx context.Context, in *TUser, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/YACS5e/Registration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yACS5EClient) Login(ctx context.Context, in *TUser, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/YACS5e/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yACS5EClient) Synchronize(ctx context.Context, opts ...grpc.CallOption) (YACS5E_SynchronizeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_YACS5E_serviceDesc.Streams[0], c.cc, "/YACS5e/Synchronize", opts...)
	if err != nil {
		return nil, err
	}
	x := &yACS5ESynchronizeClient{stream}
	return x, nil
}

type YACS5E_SynchronizeClient interface {
	Send(*TTalk) error
	Recv() (*TTalk, error)
	grpc.ClientStream
}

type yACS5ESynchronizeClient struct {
	grpc.ClientStream
}

func (x *yACS5ESynchronizeClient) Send(m *TTalk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *yACS5ESynchronizeClient) Recv() (*TTalk, error) {
	m := new(TTalk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for YACS5E service

type YACS5EServer interface {
	Registration(context.Context, *TUser) (*Empty, error)
	Login(context.Context, *TUser) (*Empty, error)
	Synchronize(YACS5E_SynchronizeServer) error
}

func RegisterYACS5EServer(s *grpc.Server, srv YACS5EServer) {
	s.RegisterService(&_YACS5E_serviceDesc, srv)
}

func _YACS5E_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YACS5EServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/YACS5e/Registration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YACS5EServer).Registration(ctx, req.(*TUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _YACS5E_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YACS5EServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/YACS5e/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YACS5EServer).Login(ctx, req.(*TUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _YACS5E_Synchronize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(YACS5EServer).Synchronize(&yACS5ESynchronizeServer{stream})
}

type YACS5E_SynchronizeServer interface {
	Send(*TTalk) error
	Recv() (*TTalk, error)
	grpc.ServerStream
}

type yACS5ESynchronizeServer struct {
	grpc.ServerStream
}

func (x *yACS5ESynchronizeServer) Send(m *TTalk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *yACS5ESynchronizeServer) Recv() (*TTalk, error) {
	m := new(TTalk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _YACS5E_serviceDesc = grpc.ServiceDesc{
	ServiceName: "YACS5e",
	HandlerType: (*YACS5EServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registration",
			Handler:    _YACS5E_Registration_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _YACS5E_Login_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synchronize",
			Handler:       _YACS5E_Synchronize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "yacs5e.proto",
}

func init() { proto.RegisterFile("yacs5e.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0xd7, 0x25, 0x49, 0x9b, 0xc9, 0xc2, 0x61, 0xb4, 0x82, 0x50, 0x56, 0xa8, 0xf4, 0x54,
	0x84, 0x14, 0xa1, 0xa2, 0xfd, 0x01, 0x74, 0x85, 0xb4, 0x07, 0x40, 0x2b, 0x6f, 0x38, 0x70, 0xaa,
	0xdc, 0xc4, 0x4a, 0xad, 0x4d, 0x6c, 0x63, 0x3b, 0xa0, 0x70, 0xe6, 0xc2, 0xbf, 0x46, 0x76, 0x02,
	0x45, 0x7b, 0xca, 0xbc, 0xf7, 0x46, 0x93, 0x2f, 0x93, 0x81, 0xf3, 0x81, 0x55, 0xf6, 0x8a, 0x17,
	0xda, 0x28, 0xa7, 0xd6, 0xbf, 0x09, 0xc4, 0xe5, 0x17, 0xcb, 0x0d, 0x5e, 0x40, 0xdc, 0xaa, 0x46,
	0xc8, 0x9c, 0xac, 0xc8, 0x26, 0xa5, 0xa3, 0xc0, 0x25, 0x2c, 0x34, 0xb3, 0xf6, 0x87, 0x32, 0x75,
	0x3e, 0x0b, 0xc1, 0x3f, 0x8d, 0x4f, 0x60, 0x26, 0xea, 0xfc, 0xd1, 0x8a, 0x6c, 0x1e, 0xd3, 0x99,
	0xa8, 0xf1, 0x12, 0x52, 0xc3, 0xad, 0x2e, 0xd5, 0x3d, 0x97, 0x79, 0x14, 0x9a, 0x4f, 0x06, 0xae,
	0x20, 0xfb, 0x2e, 0xac, 0x38, 0xb4, 0xfc, 0x33, 0xeb, 0x78, 0x1e, 0x87, 0xfc, 0x7f, 0x6b, 0xfd,
	0x8b, 0x00, 0x94, 0xd7, 0x47, 0x66, 0x58, 0xe5, 0xb8, 0x41, 0x84, 0xa8, 0xef, 0x45, 0x3d, 0xf1,
	0x84, 0x1a, 0x5f, 0x40, 0xda, 0x32, 0xeb, 0xf6, 0x76, 0x90, 0x55, 0xe0, 0x89, 0xe8, 0xc2, 0x1b,
	0x77, 0x83, 0xac, 0xf0, 0x39, 0x84, 0x7a, 0xdf, 0xa9, 0x91, 0x2a, 0xa2, 0x73, 0xaf, 0x3f, 0xa9,
	0xda, 0xcf, 0x3a, 0xb4, 0xea, 0x30, 0x51, 0x85, 0x1a, 0x9f, 0x42, 0x52, 0xf3, 0x96, 0xbb, 0x91,
	0x65, 0x41, 0x27, 0xb5, 0xfe, 0x06, 0x71, 0x59, 0xb2, 0xf6, 0x1e, 0x2f, 0x21, 0xea, 0x2d, 0x37,
	0x01, 0x20, 0xdb, 0x26, 0x45, 0xd8, 0xd3, 0xcd, 0x19, 0x0d, 0x2e, 0xbe, 0x81, 0xb4, 0xfa, 0xcb,
	0x1a, 0x50, 0xb2, 0x6d, 0x56, 0x9c, 0xf0, 0x6f, 0xce, 0xe8, 0x29, 0xc7, 0x0b, 0x88, 0x1a, 0x35,
	0x61, 0x2d, 0xfc, 0x08, 0xaf, 0x76, 0x73, 0x88, 0x7b, 0x29, 0x94, 0x5c, 0xcf, 0x21, 0xfe, 0xd0,
	0x69, 0x37, 0x6c, 0x6b, 0x48, 0xbe, 0xbe, 0xbf, 0xbe, 0xbb, 0xe2, 0xf8, 0x12, 0xce, 0x29, 0x6f,
	0x84, 0x75, 0x86, 0x39, 0xa1, 0x24, 0x4e, 0xaf, 0x5f, 0x26, 0x45, 0xe8, 0xc4, 0x67, 0x10, 0x7f,
	0x0c, 0x7f, 0xe8, 0x61, 0xf0, 0x0a, 0x32, 0xbf, 0x8d, 0xa3, 0x51, 0x52, 0xfc, 0xe4, 0x3e, 0xf6,
	0x1f, 0xb3, 0x9c, 0x9e, 0x1b, 0xf2, 0x96, 0xec, 0x5e, 0xc3, 0xb2, 0x52, 0x5d, 0xa1, 0x9d, 0x76,
	0x47, 0x21, 0x1b, 0x6e, 0x6c, 0x31, 0x1e, 0xc5, 0x9e, 0x69, 0xbd, 0x4b, 0x3d, 0xc1, 0xad, 0xbf,
	0x8e, 0x5b, 0x72, 0x48, 0xc2, 0x99, 0xbc, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xee, 0xfb,
	0x8c, 0x36, 0x02, 0x00, 0x00,
}
